// Code generated by "stringer -type=tokenType -trimprefix=token"; DO NOT EDIT.

package template

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenError-0]
	_ = x[tokenEOF-1]
	_ = x[tokenChar-2]
	_ = x[tokenComment-3]
	_ = x[tokenIdent-4]
	_ = x[tokenString-5]
	_ = x[tokenNumber-6]
	_ = x[tokenLeftDelim-7]
	_ = x[tokenRightDelim-8]
	_ = x[tokenLeftParen-9]
	_ = x[tokenRightParen-10]
	_ = x[tokenLeftBrack-11]
	_ = x[tokenRightBrack-12]
	_ = x[tokenLeftBrace-13]
	_ = x[tokenRightBrace-14]
	_ = x[tokenComma-15]
	_ = x[tokenPeriod-16]
	_ = x[tokenAt-17]
	_ = x[tokenAssign-18]
	_ = x[tokenLT-19]
	_ = x[tokenLE-20]
	_ = x[tokenEQ-21]
	_ = x[tokenNE-22]
	_ = x[tokenGT-23]
	_ = x[tokenGE-24]
	_ = x[tokenConcat-25]
	_ = x[tokenAdd-26]
	_ = x[tokenSub-27]
	_ = x[tokenMul-28]
	_ = x[tokenFloatDiv-29]
	_ = x[tokenBitAnd-30]
	_ = x[tokenBitOr-31]
	_ = x[tokenBitXor-32]
	_ = x[tokenBitNot-33]
	_ = x[tokenSemicolon-34]
	_ = x[tokenCreate-35]
	_ = x[tokenTable-36]
	_ = x[tokenOr-37]
	_ = x[tokenAnd-38]
	_ = x[tokenNot-39]
	_ = x[tokenIs-40]
	_ = x[tokenRowNum-41]
	_ = x[tokenSubRowNum-42]
	_ = x[tokenNull-43]
	_ = x[tokenTrue-44]
	_ = x[tokenFalse-45]
	_ = x[tokenCase-46]
	_ = x[tokenWhen-47]
	_ = x[tokenThen-48]
	_ = x[tokenElse-49]
	_ = x[tokenEnd-50]
	_ = x[tokenTimestamp-51]
	_ = x[tokenInterval-52]
	_ = x[tokenWeek-53]
	_ = x[tokenDay-54]
	_ = x[tokenHour-55]
	_ = x[tokenMinute-56]
	_ = x[tokenSecond-57]
	_ = x[tokenMillisecond-58]
	_ = x[tokenMicrosecond-59]
	_ = x[tokenWith-60]
	_ = x[tokenTime-61]
	_ = x[tokenZone-62]
	_ = x[tokenSubstring-63]
	_ = x[tokenFrom-64]
	_ = x[tokenFor-65]
	_ = x[tokenUsing-66]
	_ = x[tokenCharacters-67]
	_ = x[tokenOctets-68]
	_ = x[tokenOverlay-69]
	_ = x[tokenPlacing-70]
	_ = x[tokenCurrentTimestamp-71]
	_ = x[tokenArray-72]
	_ = x[tokenEach-73]
	_ = x[tokenRow-74]
	_ = x[tokenOf-75]
	_ = x[tokenGenerate-76]
	_ = x[tokenRows-77]
	_ = x[tokenX-78]
}

const _tokenType_name = "ErrorEOFCharCommentIdentStringNumberLeftDelimRightDelimLeftParenRightParenLeftBrackRightBrackLeftBraceRightBraceCommaPeriodAtAssignLTLEEQNEGTGEConcatAddSubMulFloatDivBitAndBitOrBitXorBitNotSemicolonCreateTableOrAndNotIsRowNumSubRowNumNullTrueFalseCaseWhenThenElseEndTimestampIntervalWeekDayHourMinuteSecondMillisecondMicrosecondWithTimeZoneSubstringFromForUsingCharactersOctetsOverlayPlacingCurrentTimestampArrayEachRowOfGenerateRowsX"

var _tokenType_index = [...]uint16{0, 5, 8, 12, 19, 24, 30, 36, 45, 55, 64, 74, 83, 93, 102, 112, 117, 123, 125, 131, 133, 135, 137, 139, 141, 143, 149, 152, 155, 158, 166, 172, 177, 183, 189, 198, 204, 209, 211, 214, 217, 219, 225, 234, 238, 242, 247, 251, 255, 259, 263, 266, 275, 283, 287, 290, 294, 300, 306, 317, 328, 332, 336, 340, 349, 353, 356, 361, 371, 377, 384, 391, 407, 412, 416, 419, 421, 429, 433, 434}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
