// Code generated by "stringer -type=Kind -trimprefix=Kind"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindNull-0]
	_ = x[KindBool-1]
	_ = x[KindBytes-2]
	_ = x[KindInt-3]
	_ = x[KindFloat-4]
	_ = x[KindTimestamp-5]
	_ = x[KindInterval-6]
	_ = x[KindArray-7]
}

const _Kind_name = "NullBoolBytesIntFloatTimestampIntervalArray"

var _Kind_index = [...]uint8{0, 4, 8, 13, 16, 21, 30, 38, 43}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
